[package]
name = "cw"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]
license = "MIT"
description = "Count Words, a wc clone"
readme = "README.md"
repository = "https://github.com/Freaky/cw"
keywords = ["wc", "word", "count"]
categories = [ "command-line-utilities", "text-processing" ]
edition = "2018"

[dependencies]
bytecount = "0.4.0"
structopt = "0.2.14"
libc = "0.2.46"

[features]
runtime-dispatch-simd = ["bytecount/runtime-dispatch-simd"]
generic-simd = ["bytecount/generic-simd"]
